name:                alchemy
version:             0.1.0.0
github:              "ceigh/alchemy"
license:             BSD3
author:              "Artjom Löbsack"
maintainer:          "me@ceigh.com"
copyright:           "2020 Artjom Löbsack"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ceigh/alchemy#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  alchemy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - alchemy

tests:
  alchemy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - alchemy
