name: alchemy
version: 0.1.0
github: "ceigh/alchemy"
license: MIT
author: "Artjom Löbsack"
maintainer: "me@ceigh.com"
copyright: "2020 Artjom Löbsack"

synopsis: Common alchemy game
category: Games
extra-source-files:
- README
- CHANGELOG

description: See README at https://github.com/ceigh/alchemy

dependencies:
- base >= 4.7 && < 5
- brick >= 0.52.1 && < 1
- microlens >= 0.4.11.2 && < 1
- microlens-th >= 0.4.3.6 && < 1
- yaml >= 0.11.5.0 && < 1
- bytestring >= 0.10.10.1 && < 1
- pretty-simple >= 3.2.3.0 && < 5

library:
  source-dirs: src

executables:
  alchemy-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - alchemy
